version: "3.5"

services:
  server:
    image: nginx:latest
    container_name: ${project_prefix}_server
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    networks:
      - ${project_prefix}_network